# This rule is not used by the project simple-k8s-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to home.home.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: simple-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: backup-viewer-role
rules:
- apiGroups:
  - home.home.com
  resources:
  - backups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - home.home.com
  resources:
  - backups/status
  verbs:
  - get
