apiVersion: home.home.com/v1
kind: Backup
metadata:
  labels:
    app.kubernetes.io/name: simple-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: backup-sample
spec:
  # TODO(user): Add fields here
